### PR TITLE
Upgrade @esbuild-kit/core-utils to 0.3.1

### PR DESCRIPTION
**Pull request by noomly**
This PR simply upgrades `core-utils` in order to support new features from Typescript 5.0.

The tests all pass and I didn't have any issues testing it on a personal project that makes use of the new `const T` feature. Although, if you feel like there is something else that I missed and needs to be done for this PR to be merged I'm all ears!

### CODE REVIEW

**Comment by privatenumber** [comment]
Is there a specific problem you're encountering with this PR?

**Comment by noomly** [comment]
As I mentioned, Typescript 5.0 has new features that are not supported by the esbuild's version shipped with @esbuild-kit/core-utils 0.3.0 - that tsx currently uses - but that are supported by the version shipped with @esbuild-kit/core-utils 0.3.1; hence this PR.

These new features include for example [const Type parameters](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/#const-type-parameters). Support for this feature was specifically implemented in esbuild [0.17.5](https://github.com/evanw/esbuild/releases/tag/v0.17.5), as mentioned in this comment: https://github.com/esbuild-kit/tsx/issues/171#issuecomment-1406967995.

**Comment by privatenumber** [comment]
The changes in this PR are unnecessary, so I was curious what specific issue you're encountering.

> These new features include for example [const Type parameters](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/#const-type-parameters). Support for this feature was specifically implemented in esbuild [0.17.5](https://github.com/evanw/esbuild/releases/tag/v0.17.5), as mentioned in this comment: [#171 (comment)](https://github.com/esbuild-kit/tsx/issues/171#issuecomment-1406967995).

The new `const` type parameter woks fine on tsx. Try creating a reproduction from the issue template, and if that doesn't work, you can file a bug. Also read https://github.com/esbuild-kit/tsx/issues/171#issuecomment-1374704346

**Comment by noomly** [comment]
I see why it's not necessary, sorry for the noise.

**Pull request closed without merging**
