### PR TITLE
feat: support Node v20.6.0 `module.register()` & `--import` flag

### PR DESCRIPTION
**Pull request by privatenumber**
closes https://github.com/esbuild-kit/tsx/issues/330

### CODE REVIEW

**Comment by vladshcherbin** [comment]
Any change or timeline to drop this one? 🤞

**Comment by privatenumber** [comment]
:tada: This issue has been resolved in v3.14.0

If you appreciate this project, please consider [supporting this project by sponsoring](https://github.com/sponsors/privatenumber) :heart: :pray:

**Comment by vladshcherbin** [comment]
@privatenumber thank you a lot! 🤗

**Comment by privatenumber** [comment]
Hope it works well for you!

**Comment by vladshcherbin** [comment]
@privatenumber I've updated and the warning are gone 🥳

Thank you for your work, `tsx` is such a relief in js/ts land, much love ♥️

**Pull request merged**
